WebAppUI/Models/ProductViewModel.cs
using Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppUI.Models
{
    public class ProductViewModel
    {
        public List<Product> products{ get; set; }

        public int Id { get; set; }
        [Required(ErrorMessage = "Barkod bilgisi giriniz.")]
        public string Barcode { get; set; }

        [Required(ErrorMessage = "Fiyat bilgisi giriniz.")]
        public int Price { get; set; }

        [Required(ErrorMessage = "Resim bilgisi giriniz.")]
        public string ImageUrl { get; set; }

        [Required(ErrorMessage = "Açıklama bilgisi giriniz.")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Adet bilgisi giriniz.")]
        public int Piece { get; set; }

    }
}

WebAppUI/ViewComponents/UserSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using WebAppUI.Models;

namespace Abc.Northwind.MvcWebUI.ViewComponents
{
    public class UserSummaryViewComponent:ViewComponent
    {
        public ViewViewComponentResult Invoke()
        {
            UserDetailViewModel model = new UserDetailViewModel
            {
               UserName = HttpContext.User.Identity.Name
            };
            return View(model);
        }
    }
}

WebAppUI/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="/jquery_/dist/jquery.min.js"></script>
    <script src="/bootstrap/dist/js/bootstrap.js"></script>
    <script src="/jquery-validation/dist/jquery.validate.js"></script>
    <script src="/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <div class="col-md-12">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">ÜRÜNLER</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User <span class="caret"></span></a>
                            @await Component.InvokeAsync("UserSummary")
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div>
    <div class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-info" role="alert">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
    <div class="col-md-12"></div>
 
</body>
</html>

WebAppUI/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"/>
    <title>E Ticaret Uygulaması</title>
</head>
<body>
    
    <partial name="_navBar" />
    @RenderBody()

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" ></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" ></script>

</body>
</html>

WebAppUI/Views/Shared/_navBar.cshtml
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a asp-controller="Home" asp-action="Index" class="nav-link">ÜRÜNLER</a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="Index" class="nav-link">ADMİN</a>
                        </li>
                    }
                }
            </ul>

            <ul class="nav navbar-nav navbar-right">
                @if (User.Identity.IsAuthenticated == false)
                {
                    <li class="nav-item">
                        <a asp-controller="Account" asp-action="Login" class="nav-link">Login</a>
                    </li>
                }
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User <span class="caret"></span></a>
                        @await Component.InvokeAsync("UserSummary")
                    </li>
                }
                </ul>
        </div>
    </nav>
</div>

WebAppUI/Views/Shared/_product.cshtml
@model Product
<div class="col-md-3" style="margin-top:2%">
    <div class="card">
        <div class="view zoom overlay">
            <img class="img-fluid w-100" src="~/images/@Model.ImageUrl" alt="@Model.ImageUrl">
        </div>
        <div class="card-body text-center">

            <h5>Stokta son @Model.Piece adet kaldı.</h5>
            <p class="small text-muted text-uppercase mb-2">@Model.Description</p>
            <hr>
            <h6 class="mb-3">
                <span class="text-danger mr-1"><i class="fas fa-lira-sign"></i>@Model.Price</span>
            </h6>
            <hr>
            <p class="small text-muted text-uppercase mb-2">Barkot: @Model.Barcode</p>
        </div>

    </div>
</div>
<!-- Card --> 